# Generated by Django 5.0.6 on 2024-07-13 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0006_detalle_venta_delete_productomagic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 16, 47, 9, 112342)),
        ),
    ]
