# Generated by Django 5.0.6 on 2024-07-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0009_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
