# Generated by Django 5.0.6 on 2024-07-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0010_remove_venta_cliente_delete_detalle_delete_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosglobales',
            name='stack',
            field=models.IntegerField(null=True),
        ),
    ]
