# Generated by Django 5.0.6 on 2024-07-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0012_productosvarios_remove_productosglobales_stack_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 17, 16, 59029)),
        ),
    ]
