# Generated by Django 5.0.6 on 2024-07-13 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0013_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 17, 19, 9, 545206)),
        ),
    ]
