# Generated by Django 5.0.6 on 2024-07-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGPAGE', '0014_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCGPAGE.productosvarios'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductosGlobales',
        ),
    ]
